// ============================================================
// DSA-HUB — Data Layer 
// Single Source of Truth for App Navigation & Code Snippets
// ============================================================

const DSA = {
  topics: [
    { id: 'home', icon: '⬡', name: 'Home', desc: 'Main dashboard' },
    { id: 'complexity', icon: '⏱', name: 'Time & Space Complexity', desc: 'Measuring algorithm efficiency with Big-O notation', difficulty: 'easy' },
    { id: 'arrays', icon: '▦', name: 'Arrays', desc: 'The most fundamental — contiguous memory storage', difficulty: 'easy' },
    { id: 'linkedlist', icon: '⛓', name: 'Linked Lists', desc: 'Dynamic nodes connected via pointers', difficulty: 'medium' },
    { id: 'stack', icon: '📚', name: 'Stacks', desc: 'Last In, First Out (LIFO) — like a stack of plates', difficulty: 'easy' },
    { id: 'queue', icon: '🎫', name: 'Queues', desc: 'First In, First Out (FIFO) — like a ticket line', difficulty: 'easy' },
    { id: 'trees', icon: '🌳', name: 'Trees & BST', desc: 'Hierarchical data with parent-child relationships', difficulty: 'medium' },
    { id: 'graphs', icon: '🕸', name: 'Graphs', desc: 'Vertices connected by edges — the most versatile DS', difficulty: 'hard' },
    { id: 'hashing', icon: '#', name: 'Hashing', desc: 'O(1) average access using hash functions', difficulty: 'medium' },
    { id: 'sorting', icon: '⇅', name: 'Sorting Algorithms', desc: 'From O(n²) basics to O(n log n) champions', difficulty: 'medium' },
    { id: 'searching', icon: '🔍', name: 'Searching Algorithms', desc: 'Finding elements efficiently', difficulty: 'easy' },
    { id: 'recursion', icon: '🔄', name: 'Recursion', desc: 'A function that calls itself to solve smaller sub-problems', difficulty: 'medium' },
    { id: 'dp', icon: '🧮', name: 'Dynamic Programming', desc: 'Memoize overlapping subproblems for speed', difficulty: 'hard' },
    { id: 'heap', icon: '⛰', name: 'Heap / Priority Queue', desc: 'Complete binary tree with heap property', difficulty: 'medium' },
    { id: 'trie', icon: '🔤', name: 'Trie', desc: 'Prefix tree for O(L) string operations', difficulty: 'hard' },
    { id: 'realworld', icon: '⊕', name: 'Real World Uses', desc: 'Everyday applications of Data Structures and Algorithms', difficulty: 'easy' }
  ],
  code: {
    array_basics: {
      c: `int arr[5] = {10, 20, 30, 40, 50};\n\n// Access — O(1)\nint x = arr[2]; // x = 30\n\n// Traverse — O(n)\nfor(int i=0; i<5; i++) {\n    printf("%d ", arr[i]);\n}\n\n// Delete at index k — shift left O(n)\nfor(int j=k; j<n-1; j++) {\n    arr[j] = arr[j+1];\n}\nn--;\n\n// 2D Array (3×3 matrix)\nint mat[3][3] = {\n    {1,2,3},\n    {4,5,6},\n    {7,8,9}\n};`,
      cpp: `#include <iostream>\n#include <vector>\nusing namespace std;\n\nint main() {\n    vector<int> arr = {10, 20, 30, 40, 50};\n\n    // Access — O(1)\n    int x = arr[2];\n\n    // Traverse — O(n)\n    for(int v : arr) {\n        cout << v << " ";\n    }\n\n    // Delete at index k — shift left O(n)\n    int k = 2;\n    arr.erase(arr.begin() + k);\n\n    // 2D Array\n    vector<vector<int>> mat = {\n        {1,2,3},\n        {4,5,6},\n        {7,8,9}\n    };\n    return 0;\n}`,
      js: `let arr = [10, 20, 30, 40, 50];\n\n// Access — O(1)\nlet x = arr[2]; // x = 30\n\n// Traverse — O(n)\narr.forEach(v => console.log(v));\n\n// Delete at index k — built-in splice O(n)\nlet k = 2;\narr.splice(k, 1);\n\n// 2D Array (3×3 matrix)\nlet mat = [\n    [1, 2, 3],\n    [4, 5, 6],\n    [7, 8, 9]\n];`
    },
    linkedlist_basics: {
      c: `struct Node { \n    int data; \n    struct Node* next; \n};\n\nstruct Node* newNode(int val) {\n    struct Node* n = malloc(sizeof(struct Node));\n    n->data = val; \n    n->next = NULL;\n    return n;\n}\n\n// Insert at front — O(1)\nvoid insertFront(struct Node** head, int val) {\n    struct Node* n = newNode(val);\n    n->next = *head; \n    *head = n;\n}\n\n// Traverse & print — O(n)\nvoid print(struct Node* head) {\n    while(head) { \n        printf("%d→", head->data); \n        head = head->next; \n    }\n    printf("NULL\\n");\n}`,
      cpp: `#include <iostream>\nusing namespace std;\n\nstruct Node { \n    int data; \n    Node* next; \n    Node(int val) : data(val), next(nullptr) {}\n};\n\n// Insert at front — O(1)\nvoid insertFront(Node*& head, int val) {\n    Node* n = new Node(val);\n    n->next = head; \n    head = n;\n}\n\n// Traverse & print — O(n)\nvoid print(Node* head) {\n    while(head) { \n        cout << head->data << "→"; \n        head = head->next; \n    }\n    cout << "NULL\\n";\n}`,
      js: `class Node {\n    constructor(val) {\n        this.data = val;\n        this.next = null;\n    }\n}\n\nlet head = null;\n\n// Insert at front — O(1)\nfunction insertFront(val) {\n    let n = new Node(val);\n    n.next = head;\n    head = n;\n}\n\n// Traverse & print — O(n)\nfunction printList(node) {\n    let out = [];\n    while(node) {\n        out.push(node.data);\n        node = node.next;\n    }\n    console.log(out.join(' → ') + ' → null');\n}`
    },
    stack_basics: {
      c: `#define MAX 100\nstruct Stack { int items[MAX], top; };\nvoid init(struct Stack* s) { s->top = -1; }\n\n// Push — O(1)\nvoid push(struct Stack* s, int v) {\n    if(s->top == MAX-1) { printf("Overflow!\\n"); return; }\n    s->items[++s->top] = v;\n}\n\n// Pop — O(1)\nint pop(struct Stack* s) {\n    if(s->top == -1) { printf("Underflow!\\n"); return -1; }\n    return s->items[s->top--];\n}`,
      cpp: `#include <iostream>\n#include <stack>\nusing namespace std;\n\nint main() {\n    stack<int> s;\n\n    // Push — O(1)\n    s.push(10);\n    s.push(20);\n\n    // Peek top element — O(1)\n    cout << "Top: " << s.top() << endl;\n\n    // Pop — O(1)\n    s.pop();\n    \n    if (s.empty()) {\n        cout << "Stack is empty\\n";\n    }\n    return 0;\n}`,
      js: `let stack = [];\n\n// Push — O(1)\nstack.push(10);\nstack.push(20);\n\n// Peek top element — O(1)\nlet topVal = stack[stack.length - 1];\nconsole.log("Top:", topVal);\n\n// Pop — O(1)\nlet popped = stack.pop();\n\nif (stack.length === 0) {\n    console.log("Stack is empty");\n}`
    },
    queue_basics: {
      c: `#define MAX 100\nstruct Queue { int items[MAX], front, rear; };\nvoid init(struct Queue* q) { q->front = q->rear = -1; }\n\n// Enqueue — O(1)\nvoid enqueue(struct Queue* q, int v) {\n    if(q->rear == MAX-1) { printf("Full!\\n"); return; }\n    if(q->front == -1) q->front = 0;\n    q->items[++q->rear] = v;\n}\n\n// Dequeue — O(1)\nint dequeue(struct Queue* q) {\n    if(q->front == -1) { printf("Empty!\\n"); return -1; }\n    int v = q->items[q->front++];\n    if(q->front > q->rear) q->front = q->rear = -1;\n    return v;\n}`,
      cpp: `#include <iostream>\n#include <queue>\nusing namespace std;\n\nint main() {\n    queue<int> q;\n\n    // Enqueue — O(1)\n    q.push(10);\n    q.push(20);\n\n    // Peek front element — O(1)\n    cout << "Front: " << q.front() << endl;\n\n    // Dequeue — O(1)\n    q.pop();\n\n    if (q.empty()) {\n        cout << "Queue is empty\\n";\n    }\n    return 0;\n}`,
      js: `let queue = [];\n\n// Enqueue — O(1)\nqueue.push(10);\nqueue.push(20);\n\n// Peek front element — O(1)\nlet frontVal = queue[0];\nconsole.log("Front:", frontVal);\n\n// Dequeue — O(n) for JS arrays (use a pointer for O(1) in production)\nlet dequeued = queue.shift();\n\nif (queue.length === 0) {\n    console.log("Queue is empty");\n}`
    },
    bst_basics: {
      c: `struct Node { int data; struct Node *left, *right; };\n\n// Insert — O(log n) avg\nstruct Node* insert(struct Node* r, int v) {\n    if(!r) return newNode(v);\n    if(v < r->data) r->left = insert(r->left, v);\n    else if(v > r->data) r->right = insert(r->right, v);\n    return r;\n}\n\n// Inorder (sorted output!)\nvoid inorder(struct Node* r) {\n    if(!r) return;\n    inorder(r->left);\n    printf("%d ", r->data);\n    inorder(r->right);\n}`,
      cpp: `#include <iostream>\nusing namespace std;\n\nstruct Node { \n    int data; \n    Node *left, *right; \n    Node(int v) : data(v), left(nullptr), right(nullptr) {}\n};\n\n// Insert — O(log n) avg\nNode* insert(Node* r, int v) {\n    if(!r) return new Node(v);\n    if(v < r->data) r->left = insert(r->left, v);\n    else if(v > r->data) r->right = insert(r->right, v);\n    return r;\n}\n\n// Inorder (sorted output!)\nvoid inorder(Node* r) {\n    if(!r) return;\n    inorder(r->left);\n    cout << r->data << " ";\n    inorder(r->right);\n}`,
      js: `class Node {\n    constructor(val) {\n        this.data = val;\n        this.left = this.right = null;\n    }\n}\n\n// Insert — O(log n) avg\nfunction insert(root, v) {\n    if (!root) return new Node(v);\n    if (v < root.data) root.left = insert(root.left, v);\n    else if (v > root.data) root.right = insert(root.right, v);\n    return root;\n}\n\n// Inorder (sorted output!)\nfunction inorder(root) {\n    if (!root) return;\n    inorder(root.left);\n    console.log(root.data);\n    inorder(root.right);\n}`
    },
    graph_bfs_dfs: {
      c: `#define V 6\nint adj[V][V];\n\n// BFS — O(V + E)\nvoid bfs(int s) {\n    int vis[V]={0}, q[V], f=0, r=0;\n    vis[s]=1; q[r++]=s;\n    while(f<r) {\n        int v=q[f++]; printf("%d ",v);\n        for(int i=0; i<V; i++)\n            if(adj[v][i] && !vis[i]) { vis[i]=1; q[r++]=i; }\n    }\n}\n\n// DFS — O(V + E)\nvoid dfs(int v, int vis[]) {\n    vis[v]=1; printf("%d ",v);\n    for(int i=0; i<V; i++)\n        if(adj[v][i] && !vis[i]) dfs(i,vis);\n}`,
      cpp: `#include <iostream>\n#include <vector>\n#include <queue>\nusing namespace std;\n\n// BFS — O(V + E)\nvoid bfs(int start, vector<vector<int>>& adj) {\n    vector<bool> vis(adj.size(), false);\n    queue<int> q;\n    vis[start] = true; q.push(start);\n    \n    while(!q.empty()) {\n        int v = q.front(); q.pop();\n        cout << v << " ";\n        for(int neighbor : adj[v]) {\n            if(!vis[neighbor]) { vis[neighbor]=true; q.push(neighbor); }\n        }\n    }\n}\n\n// DFS — O(V + E)\nvoid dfs(int v, vector<vector<int>>& adj, vector<bool>& vis) {\n    vis[v] = true;\n    cout << v << " ";\n    for(int neighbor : adj[v]) {\n        if(!vis[neighbor]) dfs(neighbor, adj, vis);\n    }\n}`,
      js: `// BFS — O(V + E)\nfunction bfs(start, adjList) {\n    let vis = new Set();\n    let q = [start];\n    vis.add(start);\n    \n    while(q.length > 0) {\n        let v = q.shift();\n        console.log(v);\n        for(let neighbor of adjList[v]) {\n            if(!vis.has(neighbor)) {\n                vis.add(neighbor);\n                q.push(neighbor);\n            }\n        }\n    }\n}\n\n// DFS — O(V + E)\nfunction dfs(v, adjList, vis = new Set()) {\n    vis.add(v);\n    console.log(v);\n    for(let neighbor of adjList[v]) {\n        if(!vis.has(neighbor)) dfs(neighbor, adjList, vis);\n    }\n}`
    },
    hashing_basics: {
      c: `#define SIZE 7\nstruct Node { int key, val; struct Node* next; };\nstruct Node* table[SIZE] = {0};\n\nint hash(int key) { return key % SIZE; }\n\n// Insert — O(1) avg\nvoid insert(int key, int val) {\n    int idx = hash(key);\n    struct Node* n = newNode(key,val);\n    n->next = table[idx]; table[idx] = n;\n}\n\n// Search — O(1) avg, O(n) worst\nint search(int key) {\n    struct Node* c = table[hash(key)];\n    while(c){ if(c->key==key) return c->val; c=c->next; }\n    return -1;\n}`,
      cpp: `#include <iostream>\n#include <unordered_map>\nusing namespace std;\n\nint main() {\n    // C++ STL provides a Hash Table via unordered_map\n    unordered_map<string, int> map;\n\n    // Insert — O(1) avg\n    map["Alice"] = 25;\n    map["Bob"] = 30;\n\n    // Search — O(1) avg\n    if (map.find("Alice") != map.end()) {\n        cout << "Alice's age: " << map["Alice"] << endl;\n    }\n\n    // Delete — O(1) avg\n    map.erase("Bob");\n\n    return 0;\n}`,
      js: `// JavaScript has built-in hash maps via Objects and Maps\nlet map = new Map();\n\n// Insert — O(1) avg\nmap.set("Alice", 25);\nmap.set("Bob", 30);\n\n// Search — O(1) avg\nif (map.has("Alice")) {\n    console.log("Alice's age:", map.get("Alice"));\n}\n\n// Delete — O(1) avg\nmap.delete("Bob");\n\n// Iterate\nfor (let [key, val] of map) {\n    console.log(key, val);\n}`
    },
    bubble_sort: {
      c: `void bubbleSort(int arr[], int n) {\n    for (int i = 0; i < n - 1; i++) {\n        for (int j = 0; j < n - i - 1; j++) {\n            if (arr[j] > arr[j + 1]) {\n                int temp = arr[j];\n                arr[j] = arr[j + 1];\n                arr[j + 1] = temp;\n            }\n        }\n    }\n}\n\nvoid insertionSort(int arr[], int n) {\n    for (int i = 1; i < n; i++) {\n        int key = arr[i];\n        int j = i - 1;\n        while (j >= 0 && arr[j] > key) {\n            arr[j + 1] = arr[j];\n            j = j - 1;\n        }\n        arr[j + 1] = key;\n    }\n}`,
      cpp: `#include <iostream>\n#include <vector>\nusing namespace std;\n\nvoid bubbleSort(vector<int>& arr) {\n    int n = arr.size();\n    for (int i = 0; i < n - 1; i++) {\n        for (int j = 0; j < n - i - 1; j++) {\n            if (arr[j] > arr[j + 1]) {\n                swap(arr[j], arr[j + 1]);\n            }\n        }\n    }\n}\n\nvoid insertionSort(vector<int>& arr) {\n    for (size_t i = 1; i < arr.size(); i++) {\n        int key = arr[i];\n        int j = i - 1;\n        while (j >= 0 && arr[j] > key) {\n            arr[j + 1] = arr[j];\n            j--;\n        }\n        arr[j + 1] = key;\n    }\n}`,
      js: `function bubbleSort(arr) {\n    for (let i = 0; i < arr.length - 1; i++) {\n        for (let j = 0; j < arr.length - i - 1; j++) {\n            if (arr[j] > arr[j + 1]) {\n                [arr[j], arr[j+1]] = [arr[j+1], arr[j]]; // Swap\n            }\n        }\n    }\n    return arr;\n}\n\nfunction insertionSort(arr) {\n    for (let i = 1; i < arr.length; i++) {\n        let key = arr[i];\n        let j = i - 1;\n        while (j >= 0 && arr[j] > key) {\n            arr[j + 1] = arr[j];\n            j--;\n        }\n        arr[j + 1] = key;\n    }\n    return arr;\n}`
    },
    merge_sort: {
      c: `void merge(int a[], int l, int m, int r) {\n    int n1=m-l+1, n2=r-m, L[n1], R[n2], i=0,j=0,k=l;\n    for(int x=0; x<n1; x++) L[x]=a[l+x];\n    for(int x=0; x<n2; x++) R[x]=a[m+1+x];\n    while(i<n1 && j<n2) a[k++]=L[i]<=R[j]?L[i++]:R[j++];\n    while(i<n1) a[k++]=L[i++];\n    while(j<n2) a[k++]=R[j++];\n}\n\nvoid mergeSort(int a[], int l, int r) {\n    if(l<r) {\n        int m=l+(r-l)/2;\n        mergeSort(a,l,m); mergeSort(a,m+1,r); merge(a,l,m,r);\n    }\n}`,
      cpp: `#include <vector>\nusing namespace std;\n\nvoid merge(vector<int>& a, int l, int m, int r) {\n    vector<int> L(a.begin() + l, a.begin() + m + 1);\n    vector<int> R(a.begin() + m + 1, a.begin() + r + 1);\n    int i = 0, j = 0, k = l;\n    while(i < L.size() && j < R.size())\n        a[k++] = (L[i] <= R[j]) ? L[i++] : R[j++];\n    while(i < L.size()) a[k++] = L[i++];\n    while(j < R.size()) a[k++] = R[j++];\n}\n\nvoid mergeSort(vector<int>& a, int l, int r) {\n    if(l < r) {\n        int m = l + (r - l) / 2;\n        mergeSort(a, l, m);\n        mergeSort(a, m + 1, r);\n        merge(a, l, m, r);\n    }\n}`,
      js: `function mergeSort(arr) {\n    if (arr.length <= 1) return arr;\n    \n    const mid = Math.floor(arr.length / 2);\n    const left = mergeSort(arr.slice(0, mid));\n    const right = mergeSort(arr.slice(mid));\n    \n    return merge(left, right);\n}\n\nfunction merge(left, right) {\n    let res = [], i = 0, j = 0;\n    while (i < left.length && j < right.length) {\n        if (left[i] <= right[j]) res.push(left[i++]);\n        else res.push(right[j++]);\n    }\n    return res.concat(left.slice(i)).concat(right.slice(j));\n}`
    },
    binary_search: {
      c: `// Binary Search — O(log n)\nint binarySearch(int arr[], int n, int key) {\n    int lo=0, hi=n-1;\n    while(lo <= hi) {\n        int mid = lo + (hi-lo)/2;\n        if(arr[mid] == key) return mid;   // Found!\n        else if(arr[mid] < key) lo=mid+1; // Go right\n        else hi = mid-1;                 // Go left\n    }\n    return -1; // Not found\n}`,
      cpp: `#include <vector>\nusing namespace std;\n\n// Binary Search — O(log n)\nint binarySearch(const vector<int>& arr, int key) {\n    int lo = 0, hi = arr.size() - 1;\n    while(lo <= hi) {\n        int mid = lo + (hi - lo) / 2;\n        if(arr[mid] == key) return mid;     // Found!\n        else if(arr[mid] < key) lo = mid + 1; // Go right\n        else hi = mid - 1;                   // Go left\n    }\n    return -1; // Not found\n}`,
      js: `// Binary Search — O(log n)\nfunction binarySearch(arr, key) {\n    let lo = 0, hi = arr.length - 1;\n    while (lo <= hi) {\n        let mid = Math.floor((lo + hi) / 2);\n        if (arr[mid] === key) return mid;     // Found!\n        else if (arr[mid] < key) lo = mid + 1;  // Go right\n        else hi = mid - 1;                    // Go left\n    }\n    return -1; // Not found\n}`
    },
    recursion_examples: {
      c: `// Factorial: n! = n × (n-1)!\nint factorial(int n) {\n    if (n == 0) return 1;       // Base case\n    return n * factorial(n-1);  // Recursive\n}\n\n// Fibonacci: F(n) = F(n-1) + F(n-2)\nint fib(int n) {\n    if (n <= 1) return n;\n    return fib(n-1) + fib(n-2);\n}`,
      cpp: `// Factorial: n! = n × (n-1)!\nint factorial(int n) {\n    if (n == 0) return 1;       // Base case\n    return n * factorial(n-1);  // Recursive\n}\n\n// Fibonacci: F(n) = F(n-1) + F(n-2)\nint fib(int n) {\n    if (n <= 1) return n;\n    return fib(n-1) + fib(n-2);\n}`,
      js: `// Factorial: n! = n × (n-1)!\nfunction factorial(n) {\n    if (n === 0) return 1;       // Base case\n    return n * factorial(n - 1); // Recursive\n}\n\n// Fibonacci: F(n) = F(n-1) + F(n-2)\nfunction fib(n) {\n    if (n <= 1) return n;\n    return fib(n - 1) + fib(n - 2);\n}`
    },
    dp_examples: {
      c: `// Memoized Fibonacci — O(n)\nint memo[100];\nint fib(int n) {\n    if(n<=1) return n;\n    if(memo[n]!=-1) return memo[n]; // Cache hit!\n    return memo[n] = fib(n-1)+fib(n-2);\n}\n\n// 0/1 Knapsack — O(n×W)\nint knapsack(int W, int wt[], int val[], int n) {\n    int dp[n+1][W+1];\n    for(int i=0; i<=n; i++) for(int w=0; w<=W; w++) {\n        if(i==0||w==0) dp[i][w]=0;\n        else if(wt[i-1]<=w)\n            dp[i][w]=max(val[i-1]+dp[i-1][w-wt[i-1]], dp[i-1][w]);\n        else dp[i][w]=dp[i-1][w];\n    }\n    return dp[n][W];\n}`,
      cpp: `#include <vector>\n#include <algorithm>\nusing namespace std;\n\n// Memoized Fibonacci — O(n)\nvector<int> memo(100, -1);\nint fib(int n) {\n    if(n <= 1) return n;\n    if(memo[n] != -1) return memo[n]; // Cache hit!\n    return memo[n] = fib(n - 1) + fib(n - 2);\n}\n\n// 0/1 Knapsack — O(n×W)\nint knapsack(int W, vector<int>& wt, vector<int>& val, int n) {\n    vector<vector<int>> dp(n + 1, vector<int>(W + 1, 0));\n    for(int i = 1; i <= n; i++) {\n        for(int w = 1; w <= W; w++) {\n            if(wt[i-1] <= w)\n                dp[i][w] = max(val[i-1] + dp[i-1][w-wt[i-1]], dp[i-1][w]);\n            else dp[i][w] = dp[i-1][w];\n        }\n    }\n    return dp[n][W];\n}`,
      js: `// Memoized Fibonacci — O(n)\nlet memo = {};\nfunction fib(n) {\n    if (n <= 1) return n;\n    if (memo[n]) return memo[n]; // Cache hit!\n    return memo[n] = fib(n - 1) + fib(n - 2);\n}\n\n// 0/1 Knapsack — O(n×W)\nfunction knapsack(W, wt, val, n) {\n    let dp = Array(n + 1).fill().map(() => Array(W + 1).fill(0));\n    for(let i = 1; i <= n; i++) {\n        for(let w = 1; w <= W; w++) {\n            if(wt[i-1] <= w) {\n                dp[i][w] = Math.max(val[i-1] + dp[i-1][w-wt[i-1]], dp[i-1][w]);\n            } else {\n                dp[i][w] = dp[i-1][w];\n            }\n        }\n    }\n    return dp[n][W];\n}`
    },
    heap_basics: {
      c: `void heapifyDown(int a[], int n, int i) {\n    int lg=i, l=2*i+1, r=2*i+2;\n    if(l<n && a[l]>a[lg]) lg=l;\n    if(r<n && a[r]>a[lg]) lg=r;\n    if(lg!=i) { swap(&a[i],&a[lg]); heapifyDown(a,n,lg); }\n}\n\n// Build max heap — O(n)\nvoid buildHeap(int a[], int n) {\n    for(int i=n/2-1; i>=0; i--) heapifyDown(a,n,i);\n}\n\n// Heap Sort — O(n log n)\nvoid heapSort(int a[], int n) {\n    buildHeap(a,n);\n    for(int i=n-1; i>0; i--) { swap(&a[0],&a[i]); heapifyDown(a,i,0); }\n}`,
      cpp: `#include <vector>\n#include <algorithm>\nusing namespace std;\n\nvoid heapifyDown(vector<int>& a, int n, int i) {\n    int lg = i, l = 2*i + 1, r = 2*i + 2;\n    if(l < n && a[l] > a[lg]) lg = l;\n    if(r < n && a[r] > a[lg]) lg = r;\n    if(lg != i) { \n        swap(a[i], a[lg]); \n        heapifyDown(a, n, lg); \n    }\n}\n\n// Build max heap — O(n)\nvoid buildHeap(vector<int>& a) {\n    int n = a.size();\n    for(int i = n/2 - 1; i >= 0; i--) heapifyDown(a, n, i);\n}\n\n// Heap Sort — O(n log n)\nvoid heapSort(vector<int>& a) {\n    buildHeap(a);\n    for(int i = a.size() - 1; i > 0; i--) { \n        swap(a[0], a[i]); \n        heapifyDown(a, i, 0); \n    }\n}`,
      js: `function heapifyDown(a, n, i) {\n    let lg = i, l = 2*i + 1, r = 2*i + 2;\n    if (l < n && a[l] > a[lg]) lg = l;\n    if (r < n && a[r] > a[lg]) lg = r;\n    if (lg !== i) {\n        [a[i], a[lg]] = [a[lg], a[i]];\n        heapifyDown(a, n, lg);\n    }\n}\n\n// Build max heap — O(n)\nfunction buildHeap(a) {\n    for(let i = Math.floor(a.length / 2) - 1; i >= 0; i--) {\n        heapifyDown(a, a.length, i);\n    }\n}\n\n// Heap Sort — O(n log n)\nfunction heapSort(a) {\n    buildHeap(a);\n    for(let i = a.length - 1; i > 0; i--) {\n        [a[0], a[i]] = [a[i], a[0]];\n        heapifyDown(a, i, 0);\n    }\n}`
    },
    trie_basics: {
      c: `#define ALPHA 26\nstruct TrieNode {\n    struct TrieNode* ch[ALPHA]; int isEnd;\n};\n\nvoid insert(struct TrieNode* root, char* w) {\n    struct TrieNode* c = root;\n    while(*w) {\n        int i = *w-'a';\n        if(!c->ch[i]) c->ch[i] = newTrieNode();\n        c = c->ch[i]; w++;\n    }\n    c->isEnd = 1;\n}\n\nint search(struct TrieNode* root, char* w) {\n    struct TrieNode* c = root;\n    while(*w) {\n        int i = *w-'a';\n        if(!c->ch[i]) return 0;\n        c = c->ch[i]; w++;\n    }\n    return c->isEnd;\n}`,
      cpp: `#include <unordered_map>\n#include <string>\nusing namespace std;\n\nstruct TrieNode {\n    unordered_map<char, TrieNode*> ch;\n    bool isEnd = false;\n};\n\nvoid insert(TrieNode* root, const string& w) {\n    TrieNode* c = root;\n    for(char ch : w) {\n        if(c->ch.find(ch) == c->ch.end())\n            c->ch[ch] = new TrieNode();\n        c = c->ch[ch];\n    }\n    c->isEnd = true;\n}\n\nbool search(TrieNode* root, const string& w) {\n    TrieNode* c = root;\n    for(char ch : w) {\n        if(c->ch.find(ch) == c->ch.end())\n            return false;\n        c = c->ch[ch];\n    }\n    return c->isEnd;\n}`,
      js: `class TrieNode {\n    constructor() {\n        this.ch = {};\n        this.isEnd = false;\n    }\n}\n\nfunction insert(root, word) {\n    let c = root;\n    for (let char of word) {\n        if (!c.ch[char]) {\n            c.ch[char] = new TrieNode();\n        }\n        c = c.ch[char];\n    }\n    c.isEnd = true;\n}\n\nfunction search(root, word) {\n    let c = root;\n    for (let char of word) {\n        if (!c.ch[char]) return false;\n        c = c.ch[char];\n    }\n    return c.isEnd;\n}`
    }
  }
};